### ISSUE TITLE
No information loading on V3

### ISSUE THREAD

**Issue by kastrom** [DanielHartUK/UK-Railway-Stations-Information-Boards#10]
When I run the server and load `localhost:10080` in my browser I see the header "UK Railway Station Information Boards" but no train information:

<img width="1360" alt="No train times shown" src="https://user-images.githubusercontent.com/15103016/68144664-1192fb80-ff2c-11e9-8c39-42479e88ea87.png">

I've probably missed made a basic error so here was my install process:

- Download project
- Navigate to project folder in Terminal
- Edit `app/.env.example` to include LDBWS token and save to `app/.env`
- Run `docker-compose build`
- Run `docker-compose up`
- Navigate to `localhost:10080`
- Receive 500 Server Error
- In new Terminal window navigate to project folder and run `docker-compose exec laravel php artisan key:generate`
- Run `docker-compose exec laravel chown -R www-data:www-data /var/www`
- The server returns the page above with no train information

N.B `V2` works perfectly, I'm only seeing this with `V3` and `V3-Via-on-new-line` branches.

**Environment**
macOS 10.15
Chrome 78.0.3904.70

P.S. This is a fantastic project which I'm running on a vertical monitor at work — thanks for sharing!

**Comment by DanielHartUK** [comment]
I never completed V3, so the homepage is blank. If you know the station code, you can load the board with the following url `/departures/{station}`, so for example `http://192.168.178.5:10080/departures/man`.

Closing this issue because I'm starting work on V4 and it's unlikely V3 will ever be completed (V4 will use most of the frontend from V3, replace backend with Electron/node)
